### ISSUE TITLE
Add Curlylint to GitHub Super Linter

### ISSUE THREAD

**Issue by bazzadp** [thibaudcolas/curlylint#17]
### Is your proposal related to a problem?

I'd like to easily and automatically lint my Jinja2 templates

### Describe the solution you’d like

[GitHub has recently introduced a Super Linter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/) which is basically a collection of linters for common languages that are packaged in a Docker file that can be run from a GitHub Action to lint all your code quickly and easily without having to install packages.

It would be great if CurlyLint could be added to that. It would make it easier for people to use it and also greatly increase the visibility of this project.

### Describe alternatives you’ve considered

Installing locally works but would prefer to do it via the GitHub Super Linter.

### Additional context

They give instructions on how to add linters here: https://github.com/github/super-linter/wiki/Adding-new-language-support. Could have a go at adding it myself (and will do if you don't have time and are happy to add this), but thought it might be better coming from the maintainer of this project in case they have any questions or want any changes to allow it to be added.

**Comment by bazzadp** [comment]
Closing this for now as don't believe it's quite ready for this yet.

**Comment by thibaudcolas** [comment]
Hey @bazzadp, thank you for the suggestion, but indeed I think it wouldn’t be very productive to suggest this currently. The linter is still very experimental, and right now it’s just one of many side projects for me, so let’s see how things go.
