### ISSUE TITLE
Exclude folders/files from linting

### ISSUE THREAD

**Issue by jkevingutierrez** [thibaudcolas/curlylint#87]
### Is your proposal related to a problem?

It would be great to have the ability to exclude some folders/files. For example, being able to run something like

```sh
python3 -m curlylint . --exclude some_folder
```

### Describe the solution you’d like

Add an option `exclude` that will remove folders/files from the linter

### Describe alternatives you’ve considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by thibaudcolas** [comment]
Hi @jkevingutierrez, this looks a lot like the existing [`--exclude`](https://www.curlylint.org/docs/command-line-usage/#--exclude). Have you tried that first?
